### ISSUE TITLE
Question about mask

### ISSUE THREAD

**Issue by glorioushonor** [WU-CVGL/SCINeRF#2]
Good job! Are the 8 masks for SCI automatically generated by hardware? These masks are definitely not randomly generated; they seem to follow certain rules. If I want to use software to generate masks that meet the requirements of the SCI system for five images, how should I do it? Looking forward to your reply.

**Comment by yunhaoli2020** [comment]
Hello. Unfortunately these masks are generated randomly. But they are not "fully" random by following some certain rules. The mask generation process is regularized by the certain mask overlapping rate. Please refer to the supplementary materials of our paper for more details, which illustrates the mask generation process.

**Comment by glorioushonor** [comment]
> Hello. Unfortunately these masks are generated randomly. But they are not "fully" random by following some certain rules. The mask generation process is regularized by the certain mask overlapping rate. Please refer to the supplementary materials of our paper for more details, which illustrates the mask generation process.

Thank you for your reply. I have got it. I'm trying to generate masks based on the pseudocode in the appendix. However, I'm afraid of making mistakes. Do you have code in your library that generates masks? I haven't seemed to find it.
